services:
  backend-green:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-green
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8080"
    networks:
      - app-network

  backend-blue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-blue
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8082:8080"
    networks:
      - app-network

  frontend-green:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-green
    restart: always
    ports:
      - "8083:80"
    networks:
      - app-network

  frontend-blue:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-blue
    restart: always
    ports:
      - "8084:80"
    networks:
      - app-network

networks:
  app-network:
    external: true
