version: '3.8'

services:
  mysql:
    image: mysql:8.3.0  # 최신 안정 버전 (2025년 기준)
    container_name: mysql-container
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: liar_game_db
      MYSQL_USER: a604
      MYSQL_PASSWORD: skdaks
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - backend-net

  openvidu-server:
    image: openvidu/openvidu-server-kms:latest
    container_name: openvidu-server
    restart: always
    ports:
      - "4443:4443"
      - "5443:5443"
    environment:
      - OPENVIDU_SECRET=MY_SECRET
      - DOMAIN_OR_PUBLIC_IP=localhost
      - HTTPS=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend-net

  redis:
    image: redis:7.2.4
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend-net

volumes:
  mysql-data:
  redis-data:

networks:
  backend-net:
    driver: bridge
