INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '탄탄멘'), '탄탄면');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '크로와상'), '크루아상');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '짜장면'), '자장면');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '나초'), '나쵸');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '수프'), '스프');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '카레'), '커리');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '스키야키'), '스키야끼');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '스키야키'), '스끼야끼');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '스키야키'), '스끼야키');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '음식' AND word = '비지찌개'), '콩비지찌개');


INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '동물' AND word = '강아지'), '개');


INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '장소' AND word = '피시방'), '피씨방');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '장소' AND word = '피시방'), 'PC방');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '장소' AND word = '동사무소'), '행정복지센터');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '장소' AND word = '수족관'), '아쿠아리움');


INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '물건' AND word = '노트'), '공책');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '물건' AND word = 'USB'), '유에스비');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '물건' AND word = '프라이팬'), '후라이팬');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '물건' AND word = '접시'), '그릇');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '물건' AND word = '헤어핀'), '머리핀');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '물건' AND word = '반창고'), '밴드');


INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '나라' AND word = '튀르키예'), '터키');


INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '직업' AND word = '경찰관'), '경찰');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '직업' AND word = '개그맨'), '코미디언');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '직업' AND word = '비제이'), 'BJ');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '직업' AND word = '개발자'), '프로그래머');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '직업' AND word = '배달원'), '배달기사');


INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '스포츠' AND word = '가라테'), '가라데');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '스포츠' AND word = '가라테'), '공수도');


INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '브랜드' AND word = 'H&M'), '에이치앤엠');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '브랜드' AND word = 'H&M'), '에이치엔엠');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '브랜드' AND word = 'KFC'), '케이에프씨');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '브랜드' AND word = 'VDL'), '브이디엘');


INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '10CM - 너에게 닿기를'), '너에게 닿기를');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '제니 (JENNIE) - like JENNIE'), 'like JENNIE');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '제니 (JENNIE) - like JENNIE'), '라이크 제니');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'WOODZ - Drowning'), 'Drowning');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'WOODZ - Drowning'), '드라우닝');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '조째즈 - 모르시나요'), '모르시나요');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - TOO BAD (feat. Anderson .Paak)'), 'TOO BAD');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - TOO BAD (feat. Anderson .Paak)'), '투 배드');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - HOME SWEET HOME (feat. 태양, 대성)'), 'HOME SWEET HOME');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - HOME SWEET HOME (feat. 태양, 대성)'), '홈 스윗 홈');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - HOME SWEET HOME (feat. 태양, 대성)'), '홈 스위트 홈');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '황가람 - 나는 반딧불'), '나는 반딧불');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - 오늘만 I LOVE YOU'), '오늘만 I LOVE YOU');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - 오늘만 I LOVE YOU'), '오늘만 아이 러브 유');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'aespa - Whiplash'), 'Whiplash');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'aespa - Whiplash'), '위플레시');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'IVE - REBEL HEART'), 'REBEL HEART');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'IVE - REBEL HEART'), '레벨 하트');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '우디 (Woody) - 어제보다 슬픈 오늘'), '어제보다 슬픈 오늘');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '오반(OVAN) - Flower'), 'Flower');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '오반(OVAN) - Flower'), '플라워');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - HAPPY'), 'HAPPY');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - HAPPY'), '해피');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'LE SSERAFIM - HOT'), 'HOT');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'LE SSERAFIM - HOT'), '핫');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '로제 (ROSÉ), Bruno Mars - APT.'), 'APT.');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '로제 (ROSÉ), Bruno Mars - APT.'), 'APT');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '로제 (ROSÉ), Bruno Mars - APT.'), '아파트');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - 한 페이지가 될 수 있게'), '한 페이지가 될 수 있게');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'IVE - ATTITUDE'), 'ATTITUDE');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'IVE - ATTITUDE'), '에티튜드');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - Welcome to the Show'), 'Welcome to the Show');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - Welcome to the Show'), '웰컴 투 더 쇼');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '로이킴 - 내게 사랑이 뭐냐고 물어본다면'), '내게 사랑이 뭐냐고 물어본다면');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '로제 (ROSÉ) - toxic till the end'), 'toxic till the end');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '로제 (ROSÉ) - toxic till the end'), '토식 틸 디 엔드');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '로제 (ROSÉ) - toxic till the end'), '토씩 틸 디 엔드');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이클립스 (ECLIPSE) - 소나기'), '소나기');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이예은, 아샤트리, 전건호 - MY LOVE(2025)'), 'MY LOVE');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이예은, 아샤트리, 전건호 - MY LOVE(2025)'), '마이 러브');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이무진 - 청춘만화'), '청춘만화');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '황가람 - 미치게 그리워서'), '미치게 그리워서');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'Lady Gaga, Bruno Mars - Die With A Smile'), 'Die With A Smile');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'Lady Gaga, Bruno Mars - Die With A Smile'), '다이 위드 어 스마일');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'KiiiKiii - I DO ME'), 'I DO ME');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'KiiiKiii - I DO ME'), '아이 두 미');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - 예뻤어'), '예뻤어');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'aespa - Supernova'), 'Supernova');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'aespa - Supernova'), '수퍼노바');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 사랑은 늘 도망가'), '사랑은 늘 도망가');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이창섭 - 천상연'), '천상연');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - I Feel Good'), 'I Feel Good');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - I Feel Good'), '아이 필 굿');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - PO￦ER'), 'PO￦ER');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - PO￦ER'), '파워');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'AKMU - 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지'), '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'AKMU - 어떻게 이별까지 사랑하겠어, 널 사랑하는 거지'), '어떻게 이별까지 사랑하겠어 널 사랑하는 거지');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BABYMONSTER - DRIP'), 'DRIP');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BABYMONSTER - DRIP'), '드립');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - 123-78'), '123-78');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '순순희(지환) - 슬픈 초대장'), '슬픈 초대장');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - TAKE ME'), 'TAKE ME');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - TAKE ME'), '테이크 미');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이무진 - 청혼하지 않을 이유를 못 찾았어'), '청혼하지 않을 이유를 못 찾았어');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'TWS - 첫 만남은 계획대로 되지 않아'), '첫 만남은 계획대로 되지 않아');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '아이유 - Love wins all'), 'Love wins all');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '아이유 - Love wins all'), '러브 윈스 올');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 우리들의 블루스'), '우리들의 블루스');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'aespa - UP (KARINA Solo)'), 'UP');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'aespa - UP (KARINA Solo)'), '업');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON 외 다수 - 굿데이 2025 (텔레파시 + 달빛 창가에서)'), '굿데이 2025');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON 외 다수 - 굿데이 2025 (텔레파시 + 달빛 창가에서)'), '굿데이');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '너드커넥션 - 그대만 있다면 (여름날 우리 X 너드커넥션 (Nerd Connection))'), '그대만 있다면');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 천국보다 아름다운'), '천국보다 아름다운');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'MEOVV - HANDS UP'), 'HANDS UP');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'MEOVV - HANDS UP'), '핸즈 업');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'QWER - 내 이름 맑음'), '내 이름 맑음');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'QWER - 고민중독'), '고민중독');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '성시경 - 너의 모든 순간'), '너의 모든 순간');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - Maybe Tomorrow'), 'Maybe Tomorrow');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - Maybe Tomorrow'), '메이비 투모로우');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'ILLIT - Magnetic'), 'Magnetic');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'ILLIT - Magnetic'), '마그네틱');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'Hearts2Hearts - The Chase'), 'The Chase');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'Hearts2Hearts - The Chase'), '더 체이스');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '멜로망스 - 사랑인가 봐'), '사랑인가 봐');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - Step By Step'), 'Step By Step');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - Step By Step'), '스텝 바이 스텝');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'NewJeans - How Sweet'), 'How Sweet');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'NewJeans - How Sweet'), '하우 스위트');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이무진 - 에피소드'), '에피소드');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임재현 - 비의 랩소디'), '비의 랩소디');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 다시 만날 수 있을까'), '다시 만날 수 있을까');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - 장난쳐?'), '장난쳐?');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - 장난쳐?'), '장난쳐');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 모래 알갱이'), '모래 알갱이');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '잔나비 - 주저하는 연인들을 위해'), '주저하는 연인들을 위해');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '폴킴 - 모든 날, 모든 순간 (Every day, Every Moment)'), '모든 날, 모든 순간');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '폴킴 - 모든 날, 모든 순간 (Every day, Every Moment)'), '모든 날 모든 순간');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 온기'), '온기');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - 이렇게 좋아해 본 적이 없어요'), '이렇게 좋아해 본 적이 없어요');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '(여자)아이들 - 나는 아픈 건 딱 질색이니까'), '나는 아픈 건 딱 질색이니까');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 이제 나만 믿어요'), '이제 나만 믿어요');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '프로미스나인 - Supersonic'), 'Supersonic');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '프로미스나인 - Supersonic'), '수퍼소닉');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'IVE - I AM'), 'I AM');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'IVE - I AM'), '아이엠');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '정국 - Seven (feat. Latto) - Clean Ver.'), 'Seven');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '정국 - Seven (feat. Latto) - Clean Ver.'), '세븐');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '경서예지, 전건호 - 다정히 내 이름을 부르면'), '다정히 내 이름을 부르면');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - Home'), 'Home');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - Home'), '홈');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '박재정 - 헤어지자 말해요'), '헤어지자 말해요');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'TWS - 마음 따라 뛰는 건 멋지지 않아?'), '마음 따라 뛰는 건 멋지지 않아?');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'G-DRAGON - 무제(無題) (Untitled, 2014)'), '무제');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '방탄소년단 - 봄날'), '봄날');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '제니 (JENNIE) - Mantra'), 'Mantra');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '제니 (JENNIE) - Mantra'), '만트라');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'NewJeans - Hype Boy'), 'Hype Boy');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'NewJeans - Hype Boy'), '하입 보이');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'RESCENE - LOVE ATTACK'), 'LOVE ATTACK');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'RESCENE - LOVE ATTACK'), '러브 어택');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'PLAVE - Dash'), 'Dash');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'PLAVE - Dash'), '대시');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '범진 - 인사'), '인사');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - Next Mistake'), 'Next Mistake');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'BOYNEXTDOOR - Next Mistake'), '넥스트 미스테이크');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'DAY6 - 녹아내려요'), '녹아내려요');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이영지 - Small girl (feat. 도경수(D.O.))'), 'Small girl');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '이영지 - Small girl (feat. 도경수(D.O.))'), '스몰 걸');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 무지개'), '무지개');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'KISS OF LIFE - Sticky'), 'Sticky');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'KISS OF LIFE - Sticky'), '스티키');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '재쓰비 - 너와의 모든 지금'), '너와의 모든 지금');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - London Boy'), 'London Boy');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - London Boy'), '런던 보이');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '투모로우바이투게더 - 그날이 오면'), '그날이 오면');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '우디 - 사막에서 꽃을 피우듯'), '사막에서 꽃을 피우듯');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - Do or Die'), 'Do or Die');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - Do or Die'), '두 올 다이');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '김민석 - 취중고백'), '취중고백');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'NewJeans - Ditto'), 'Ditto');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'NewJeans - Ditto'), '디토');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '임영웅 - 인생찬가'), '인생찬가');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'aespa - Armageddon'), 'Armageddon');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'aespa - Armageddon'), '아마겟돈');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'Crush - 미안해 미워해 사랑해'), '미안해 미워해 사랑해');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '송필근 - 숙녀에게'), '숙녀에게');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'j-hope, Miguel - Sweet Dreams (feat. Miguel)'), 'Sweet Dreams');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'j-hope, Miguel - Sweet Dreams (feat. Miguel)'), '스위트 드림스');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'j-hope, Miguel - Sweet Dreams (feat. Miguel)'), '스위트 드림즈');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '도경수 - 영원해'), '영원해');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'IVE - 해야 (HEYA)'), '해야');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = 'IVE - 해야 (HEYA)'), 'HEYA');
INSERT INTO synonym (main_word_id, synonym) VALUES ((SELECT id FROM category_words WHERE category = '노래' AND word = '마크 (MARK) - 1999'), '1999');