spring:
  config:
    activate:
      on-profile: local
  datasource:
    url:       ${MYSQL_URL}
    username:  ${MYSQL_USERNAME}
    password:  ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

cookie:
  secure: false
  samesite: Lax
  
cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000

openvidu:
  url: ${OPENVIDU_URL}
  secret: ${OPENVIDU_SECRET}

logging:
  level:
      # ServiceTimeAspect 클래스가 속한 패키지 전체를 DEBUG 로
    com.ssafy.backend.global.aop.ServiceTimeAspect: DEBUG