spring:
  config:
    activate:
      on-profile: local
  datasource:
    url:       ${MYSQL_URL}
    username:  ${MYSQL_USERNAME}
    password:  ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
cookie:
  secure: false
  samesite: Lax
  
cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:3000

openvidu:
  url:    ${openvidu.url}
  secret: ${openvidu.secret}